# OPENAI
export MY_OPENAI_ORGANIZATION="org-VZ4UFc3X7ZeETQRTWOJlMKDn"
export MY_OPENAI_API_KEY="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"

# GITHUB
export GITHUB_TOKEN="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"
